apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phaseflag.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "phaseflag.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  PHASEFLAG_LOG_LEVEL: {{ .Values.api.logLevel | quote }}
  PHASEFLAG_DEPLOYMENT_MODE: {{ .Values.api.deploymentMode | quote }}
  PHASEFLAG_CORS_ORIGINS: {{ .Values.api.corsOrigins | quote }}
